[package]
name = "subnetcalc"
version = "0.1.0"
edition = "2021"

[package.metadata]
authors = ["Darryl Murley <sargetun@gmail.com>"]

[dependencies]

[[bin]]
name = "subnetcalc"
path = "src/main.rs"
